title: "AlvaroLimber"
description: "La Estadística es el Arte de contar una Historia con Datos"

#baseurl:  http://localhost:4000
baseurl: https://alvarolimber.github.io
#baseurl: https://psolymos.github.io

include: [".htaccess"]
exclude: ["README.md","LICENSE.md"]
timezone:    America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Bootswatch theme (cosmo)
bswtheme: flatly
# fancy fonts on/off
fancyfonts: true
# navbar style: inverse, transparent
navbar: transparent

disqus: petersolymos
ads: false

author: '<a href="https://alvarolimber.github.io">P&eacute;ter S&oacute;lymos</a>'
author_plain: 'Alvaro Chirino'

categories: ["Etc", "Talks", "Papers", "Code", "Tutorials"]

gems:
  - jekyll-feed
  - jekyll-sitemap