# Site settings
title: Mirada Estadística
email: achirino@aru.org.bo
description: Impulsando la cultura del dato

twitter_username: EstBolivia
github_username:  AlvaroLimber

# Build settings
markdown:    kramdown