---
title: "Planificación: Estadística. EST-104 I2022"
author: 'Docente: MS. Alvaro Chirino Gutierrez'
date: "Febrero, 2022"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Contenido

  * Estadística descriptiva
  * Probabilidad y distribuciones teóricas 
  * Muestreo
  * Distribución bivariante, regresión

  
# Planificación por fecha

```{r,echo=F}
library(readxl)
StartDate <- as.Date("2022-02-01")
EndDate <- as.Date("2022-06-17") 
myDays <- seq(StartDate , EndDate, by = "day") 
#c("lunes","martes","miércoles","jueves","viernes", "sábado","domingo")
#excludeDays <- c("martes","jueves","viernes", "sábado","domingo")
excludeDays<-c("Monday","Wednesday","Thursday","Saturday","Sunday")
myWeekDays <- subset(myDays, !weekdays(myDays) %in% excludeDays)

aux<-read_excel("G:\\My Drive\\contenido_materias\\contenido2020.xlsx",sheet = "EST104")
#aux<-read_excel("/Volumes/GoogleDrive/My Drive/contenido_materias/contenido2020.xlsx",sheet = "EST104")
aux<-cbind(aux,myWeekDays)
names(aux)[4]<-"Fecha"
knitr::kable(aux)
```

# Evaluación

  * 20% Primer Parcial (T1, T2)
  * 20% Segundo Parcial (T3, T4)
  * 20% Proyecto 
  * 30% Final (T1-T4)
  * 10% Auxiliatura
  * 5% Práctica de libro guía
