---
title: "Planificación: Estadística II. EST-145 II-2024"
author: 'Docente: MSc. Alvaro Limber Chirino Gutierrez'
date: "Agosto, 2024"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Contenido

  * Distribuciones conjuntas de probabilidad
  * Muestras aleatorias y distribuciones de muestreo
  * Estimación puntual y por intervalo
  * Prueba de hipótesis estadísticas
  
# Planificación por fecha

```{r,echo=F}
library(readxl)
StartDate <- as.Date("2024-08-01")
EndDate<-StartDate+(7*20)
#EndDate <- as.Date("2022-06-21") 
myDays <- seq(StartDate , EndDate, by = "day") 
#c("lunes","martes","miércoles","jueves","viernes", "sábado","domingo")
#excludeDays <- c("martes","jueves","viernes", "sábado","domingo")
excludeDays<-c("lunes","miércoles","viernes", "sábado","domingo")
myWeekDays <- subset(myDays, !weekdays(myDays) %in% excludeDays)
myWeekDays<-myWeekDays[1:40]
aux<-read_excel("C:\\Users\\Alvaro\\OneDrive\\_umsa\\contenido_materias\\contenido.xlsx",sheet = "EST145")
#aux<-read_excel("/Volumes/GoogleDrive/My Drive/contenido_materias/contenido2020.xlsx",sheet = "EST145")
aux<-cbind(aux,myWeekDays)
names(aux)[4]<-"Fecha"
knitr::kable(aux)
```

# Evaluación

  * 30% Primer Parcial (T1, T2)
  * 30% Segundo Parcial (T3, T4)
  * 30% Final (T1-T4)
  * 10% Auxiliatura
