---
title: "Planificación: Estadística I. EST-383 I2021"
author: 'Docente: Alvaro Chirino Gutierrez'
date: "Febrero, 2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Contenido:

  * **Tema 1:** Introducción a R
  * **Tema 2:** Introducción a Big Data
  * **Tema 3:** Scraping web
  * **Tema 4:** R y Big Data
  * **Tema 5:** R y Spark
  * **Tema 6:** Muestreo y filtrado
  
# Planificación por fecha

```{r,echo=F}
StartDate <- as.Date("2021-02-01")
EndDate <- as.Date("2021-06-17") 
myDays <- seq(StartDate , EndDate, by = "day") 
#c("lunes","martes","miércoles","jueves","viernes", "sábado","domingo")
excludeDays <- c("lunes","miércoles","viernes", "sábado","domingo")
myWeekDays <- subset(myDays, !weekdays(myDays) %in% excludeDays)
library(readxl)
aux<-read_excel("G:\\Mi unidad\\contenido_materias\\contenido2020.xlsx",sheet = "EST383rev")
aux<-cbind(aux,myWeekDays)
names(aux)[4]<-"Fecha"

knitr::kable(aux)
```

# Evaluación

	+ 25% Primer parcial: Tema 1, 2 y 3
	+ 25% Segundo parcial: Tema 4 y 5
	+ 40% Proyecto
	+ 10% Discusión
